navigation:
  - title: Scrum Lake
    url: /
  - title: What to Expect
    url: /expect
  - title: Your Facilitators
    url: /facilitators
  - title: Book a Workshop 
    url: /book

legal:
  - title: Privacy Policy
    url: /legal/privacy
  - title: Terms and Conditions
    url: /legal/terms
  - title: Copyright, Licenses and Disclaimer
    url: /legal/agreements

sales:
  - title: 7 People
    url: /7people
